WIP: Fix README and tests
ms1-learner/python-02-en pull request #1
Opened 2024-03-16 14:10 UTC by dancer-yuma

2024-03-21 06:52 UTC, dancer-yuma reviewed
Self review

2024-03-21 06:52 UTC, dancer-yuma commented on 01_intermediate_functions_and_data_structures/01_challenge/test.py
> +            extract_data(
`test_extract_data_1` and `test_extract_data_2` were testing with same kind of use cases, but each unit test should check the different use cases.

2024-03-21 06:52 UTC, dancer-yuma commented on 01_intermediate_functions_and_data_structures/01_challenge/test.py
> +if __name__ == "__main__":
Inconsistent formatting

2024-03-21 06:52 UTC, dancer-yuma commented on 02_classes_modules_and_packages/01_challenge/README.md
> +    - `retrieve_books()`: Returns a list of of dictionaries that represent books in the library.
The original instruction was expecting a dictionary with the title as key and author as value, but that is not ideal data structure given that a book could have more information.

2024-03-21 06:52 UTC, dancer-yuma commented on 02_classes_modules_and_packages/02_challenge/README.md
> +    toyota.display()
We have not covered `__str__` at this point, so it is better to implement some method to print car information.

2024-03-21 06:52 UTC, dancer-yuma commented on 02_classes_modules_and_packages/02_challenge/README.md
> +for vehicle in inventory.retrieve_vehicles():
`inventory` is not a sequence.

2024-03-21 06:52 UTC, dancer-yuma commented on 04_error_handling_and_debugging/02_challenge/event_scheduler.py
> +        if event.start_hour < 0 and event.start_hour > 24:
I added one more twist, as there was only one bug in this code.

2024-03-21 06:52 UTC, dancer-yuma commented on 04_error_handling_and_debugging/02_challenge/event_scheduler.py
> +    Event("This should not be happening", 30),
I added one line that represents an edge case.

2024-03-27 01:45 UTC, abolinsky requested changes
Just that one small fix

2024-03-27 01:45 UTC, abolinsky commented on 02_classes_modules_and_packages/01_challenge/README.md
> +    - `retrieve_books()`: Returns a list of of dictionaries that represent books in the library.
```suggestion
    - `retrieve_books()`: Returns a list of dictionaries that represents books in the library.
```

2024-03-27 01:46 UTC, abolinsky approved these changes

2024-03-27 01:46 UTC, merged